import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';

import { Button, Card, EmptyState, SelectModal, StatusBadge, Text } from '../../../components/ui';
import { CHECKLIST_TEMPLATES } from '../../../data/company';
import { generateChecklistFromTemplate } from '../../../data/mockStore';
import { useSyncStateForRecord } from '../../../data/offlineStore';
import { formatDate, personName } from '../../../data/selectors';
import { colors, spacing } from '../../../theme';
import type { Job, JobChecklist, Person } from '../../../types/domain';

interface ChecklistsSectionProps {
  job: Job;
  person: Person;
  checklists: JobChecklist[];
}

function completionPercent(c: JobChecklist): number {
  if (c.items.length === 0) return 0;
  const answered = c.items.filter((i) => i.status !== 'pending').length;
  return Math.round((answered / c.items.length) * 100);
}

export function ChecklistsSection({ job, person, checklists }: ChecklistsSectionProps) {
  const [templatePickerOpen, setTemplatePickerOpen] = useState(false);

  const availableTemplates = CHECKLIST_TEMPLATES.filter(
    (t) => !t.archived && (t.visibility === 'company' || t.createdBy === person.id)
  );

  const handleGenerate = (templateId: string) => {
    const record = generateChecklistFromTemplate({ jobId: job.id, templateId, generatedBy: person.id });
    if (record) router.push(`/(app)/checklist/${record.id}` as never);
  };

  return (
    <View>
      <View style={styles.actionRow}>
        <Text variant="footnote" color={colors.textTertiary}>
          {checklists.length} {checklists.length === 1 ? 'checklist' : 'checklists'}
        </Text>
        <Button label="Generate Checklist" size="md" fullWidth={false} onPress={() => setTemplatePickerOpen(true)} />
      </View>

      {checklists.length === 0 ? (
        <EmptyState
          icon="checkbox-outline"
          title="No checklists yet"
          message="Generate a job-specific checklist from a company template to get started."
        />
      ) : (
        checklists.map((c) => <ChecklistRow key={c.id} checklist={c} />)
      )}

      <SelectModal
        visible={templatePickerOpen}
        title="Generate Checklist"
        options={availableTemplates.map((t) => ({ label: `${t.name} · ${t.trade}`, value: t.id }))}
        selectedValue={null}
        onSelect={handleGenerate}
        onClose={() => setTemplatePickerOpen(false)}
      />
    </View>
  );
}

const SYNC_BADGE: Record<'pending' | 'syncing' | 'failed', { label: string; tone: 'neutral' | 'accent' | 'danger' }> = {
  pending: { label: 'Waiting to sync', tone: 'neutral' },
  syncing: { label: 'Syncing…', tone: 'accent' },
  failed: { label: 'Sync failed', tone: 'danger' },
};

function ChecklistRow({ checklist: c }: { checklist: JobChecklist }) {
  const percent = completionPercent(c);
  const syncState = useSyncStateForRecord(c.id);

  return (
    <Pressable onPress={() => router.push(`/(app)/checklist/${c.id}` as never)} style={styles.rowPressable}>
      {({ pressed }) => (
        <Card style={[styles.row, pressed && styles.rowPressed]} shadowToken="xs">
          <View style={styles.iconWrap}>
            <Ionicons name="checkbox-outline" size={18} color={colors.accentStrong} />
          </View>
          <View style={styles.rowBody}>
            <View style={styles.titleRow}>
              <Text variant="headline" numberOfLines={1} style={styles.title}>
                {c.templateName}
              </Text>
              <StatusBadge
                label={c.status === 'completed' ? 'Completed' : 'In Progress'}
                tone={c.status === 'completed' ? 'success' : 'warning'}
              />
              {syncState ? <StatusBadge label={SYNC_BADGE[syncState].label} tone={SYNC_BADGE[syncState].tone} /> : null}
            </View>
            <Text variant="footnote" color={colors.textSecondary} numberOfLines={1}>
              {c.trade} · {percent}% complete
            </Text>
            <Text variant="footnote" color={colors.textTertiary} numberOfLines={1}>
              Generated by {personName(c.generatedBy)} · {formatDate(c.generatedAt)}
            </Text>
          </View>
          <Ionicons name="chevron-forward" size={16} color={colors.textTertiary} />
        </Card>
      )}
    </Pressable>
  );
}

const styles = StyleSheet.create({
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  rowPressable: {
    marginBottom: spacing.sm,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md,
  },
  rowPressed: {
    opacity: 0.92,
  },
  iconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.accentMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowBody: {
    flex: 1,
    marginLeft: spacing.sm,
    marginRight: spacing.sm,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: 2,
  },
  title: {
    flexShrink: 1,
  },
});
