import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { useState, type Dispatch, type SetStateAction } from 'react';
import { Platform, Pressable, StyleSheet, View } from 'react-native';

import { Button, EmptyState, SelectModal, StatusBadge, Text } from '../../../components/ui';
import { CHECKLIST_TEMPLATES } from '../../../data/company';
import { formatDate, personName } from '../../../data/selectors';
import { createId } from '../../../lib/id';
import { colors, radius, spacing } from '../../../theme';
import type { ChecklistItemStatus, Job, JobChecklist, Person } from '../../../types/domain';

interface ChecklistsSectionProps {
  job: Job;
  person: Person;
  checklists: JobChecklist[];
  setChecklists: Dispatch<SetStateAction<JobChecklist[]>>;
}

const STATUS_CYCLE: ChecklistItemStatus[] = ['pending', 'pass', 'fail', 'na'];

const ITEM_STATUS_META: Record<ChecklistItemStatus, { label: string; color: string; icon: keyof typeof Ionicons.glyphMap }> = {
  pending: { label: 'Pending', color: colors.textTertiary, icon: 'ellipse-outline' },
  pass: { label: 'Pass', color: colors.success, icon: 'checkmark-circle' },
  fail: { label: 'Fail', color: colors.danger, icon: 'close-circle' },
  na: { label: 'N/A', color: colors.textSecondary, icon: 'remove-circle-outline' },
};

export function ChecklistsSection({ job, person, checklists, setChecklists }: ChecklistsSectionProps) {
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [templatePickerOpen, setTemplatePickerOpen] = useState(false);

  const handleGenerate = (templateId: string) => {
    const template = CHECKLIST_TEMPLATES.find((t) => t.id === templateId);
    if (!template) return;

    const now = new Date();
    const record: JobChecklist = {
      id: createId('jcl'),
      jobId: job.id,
      templateId: template.id,
      templateName: template.name,
      trade: template.trade,
      recordTitle: `${job.name} — ${template.name} — ${formatDate(now.toISOString())}`,
      generatedBy: person.id,
      generatedAt: now.toISOString(),
      status: 'in_progress',
      items: template.items.map((item) => ({ id: item.id, text: item.text, status: 'pending' })),
    };

    setChecklists((prev) => [record, ...prev]);
    setExpandedId(record.id);
    if (Platform.OS !== 'web') Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
  };

  const cycleItemStatus = (checklistId: string, itemId: string) => {
    if (Platform.OS !== 'web') Haptics.selectionAsync();
    setChecklists((prev) =>
      prev.map((c) => {
        if (c.id !== checklistId) return c;
        const items = c.items.map((item) => {
          if (item.id !== itemId) return item;
          const nextIndex = (STATUS_CYCLE.indexOf(item.status) + 1) % STATUS_CYCLE.length;
          return { ...item, status: STATUS_CYCLE[nextIndex] };
        });
        const allResolved = items.every((i) => i.status !== 'pending');
        const nowComplete = allResolved && c.status !== 'completed';
        return {
          ...c,
          items,
          status: allResolved ? 'completed' : 'in_progress',
          completedBy: allResolved ? c.completedBy ?? person.id : undefined,
          completedAt: nowComplete ? new Date().toISOString() : c.completedAt,
        };
      })
    );
  };

  return (
    <View>
      <View style={styles.actionRow}>
        <Text variant="footnote" color={colors.textTertiary}>
          {checklists.length} {checklists.length === 1 ? 'checklist' : 'checklists'}
        </Text>
        <Button
          label="Generate from Template"
          size="md"
          fullWidth={false}
          onPress={() => setTemplatePickerOpen(true)}
        />
      </View>

      {checklists.length === 0 ? (
        <EmptyState
          icon="checkbox-outline"
          title="No checklists yet"
          message="Generate a job-specific checklist from a company template to get started."
        />
      ) : (
        checklists.map((c) => {
          const expanded = expandedId === c.id;
          const passCount = c.items.filter((i) => i.status === 'pass').length;
          const failCount = c.items.filter((i) => i.status === 'fail').length;

          return (
            <View key={c.id} style={styles.card}>
              <Pressable style={styles.headerRow} onPress={() => setExpandedId(expanded ? null : c.id)}>
                <View style={styles.headerText}>
                  <Text variant="headline" numberOfLines={2}>
                    {c.recordTitle}
                  </Text>
                  <Text variant="footnote" color={colors.textTertiary} style={styles.meta}>
                    Generated by {personName(c.generatedBy)} · {formatDate(c.generatedAt)}
                  </Text>
                </View>
                <Ionicons name={expanded ? 'chevron-up' : 'chevron-down'} size={16} color={colors.textTertiary} />
              </Pressable>

              <View style={styles.badgeRow}>
                <StatusBadge
                  label={c.status === 'completed' ? 'Completed' : 'In Progress'}
                  tone={c.status === 'completed' ? 'success' : 'warning'}
                />
                <StatusBadge label={`${passCount} pass`} tone="success" />
                {failCount > 0 ? <StatusBadge label={`${failCount} fail`} tone="danger" /> : null}
              </View>

              {expanded ? (
                <View style={styles.itemList}>
                  {c.items.map((item) => {
                    const meta = ITEM_STATUS_META[item.status];
                    return (
                      <Pressable
                        key={item.id}
                        style={styles.itemRow}
                        onPress={() => cycleItemStatus(c.id, item.id)}
                      >
                        <Ionicons name={meta.icon} size={18} color={meta.color} />
                        <Text variant="body" style={styles.itemText}>
                          {item.text}
                        </Text>
                        <Text variant="caption1" color={meta.color}>
                          {meta.label}
                        </Text>
                      </Pressable>
                    );
                  })}
                  <Text variant="caption2" color={colors.textTertiary} style={styles.tapHint}>
                    Tap an item to cycle Pending → Pass → Fail → N/A
                  </Text>
                </View>
              ) : null}
            </View>
          );
        })
      )}

      <SelectModal
        visible={templatePickerOpen}
        title="Generate Checklist"
        options={CHECKLIST_TEMPLATES.map((t) => ({ label: `${t.name} · ${t.trade}`, value: t.id }))}
        selectedValue={null}
        onSelect={handleGenerate}
        onClose={() => setTemplatePickerOpen(false)}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  card: {
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.surfaceBorder,
    borderRadius: radius.md,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  headerText: {
    flex: 1,
    marginRight: spacing.sm,
  },
  meta: {
    marginTop: 2,
  },
  badgeRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginTop: spacing.sm,
    flexWrap: 'wrap',
  },
  itemList: {
    marginTop: spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.divider,
    paddingTop: spacing.sm,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.xs + 2,
  },
  itemText: {
    flex: 1,
    marginLeft: spacing.sm,
    marginRight: spacing.sm,
  },
  tapHint: {
    marginTop: spacing.xs,
  },
});
