import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';

import { Button, Card, EmptyState, SelectModal, StatusBadge, Text } from '../../../components/ui';
import { HAZARD_TEMPLATES } from '../../../data/company';
import { generateHazardAssessmentFromTemplate } from '../../../data/mockStore';
import { useSyncStateForRecord } from '../../../data/offlineStore';
import { formatDate, personName } from '../../../data/selectors';
import { colors, spacing } from '../../../theme';
import type { Job, JobHazardAssessment, Person } from '../../../types/domain';

const TOTAL_STEPS = 7;

interface HazardsSectionProps {
  job: Job;
  person: Person;
  hazards: JobHazardAssessment[];
}

function stepPercent(record: JobHazardAssessment): number {
  if (record.status === 'completed') return 100;
  return Math.round(((record.currentStep + 1) / TOTAL_STEPS) * 100);
}

export function HazardsSection({ job, person, hazards }: HazardsSectionProps) {
  const [templatePickerOpen, setTemplatePickerOpen] = useState(false);

  const availableTemplates = HAZARD_TEMPLATES.filter(
    (t) => !t.archived && (t.visibility === 'company' || t.createdBy === person.id)
  );

  const handleGenerate = (templateId: string) => {
    const record = generateHazardAssessmentFromTemplate({ jobId: job.id, templateId, generatedBy: person.id });
    if (record) router.push(`/(app)/hazard-assessment/${record.id}` as never);
  };

  return (
    <View>
      <View style={styles.actionRow}>
        <Text variant="footnote" color={colors.textTertiary}>
          {hazards.length} {hazards.length === 1 ? 'assessment' : 'assessments'}
        </Text>
        <Button
          label="Generate Hazard Assessment"
          size="md"
          fullWidth={false}
          onPress={() => setTemplatePickerOpen(true)}
        />
      </View>

      {hazards.length === 0 ? (
        <EmptyState
          icon="warning-outline"
          title="No hazard assessments yet"
          message="Generate a job-specific hazard assessment from a company template before starting work."
        />
      ) : (
        hazards.map((r) => <HazardRow key={r.id} record={r} />)
      )}

      <SelectModal
        visible={templatePickerOpen}
        title="Generate Hazard Assessment"
        options={availableTemplates.map((t) => ({ label: `${t.name} · ${t.trade}`, value: t.id }))}
        selectedValue={null}
        onSelect={handleGenerate}
        onClose={() => setTemplatePickerOpen(false)}
      />
    </View>
  );
}

const SYNC_BADGE: Record<'pending' | 'syncing' | 'failed', { label: string; tone: 'neutral' | 'accent' | 'danger' }> = {
  pending: { label: 'Waiting to sync', tone: 'neutral' },
  syncing: { label: 'Syncing…', tone: 'accent' },
  failed: { label: 'Sync failed', tone: 'danger' },
};

function HazardRow({ record: r }: { record: JobHazardAssessment }) {
  const percent = stepPercent(r);
  const identifiedCount = r.hazards.filter((h) => h.identified).length;
  const syncState = useSyncStateForRecord(r.id);

  return (
    <Pressable onPress={() => router.push(`/(app)/hazard-assessment/${r.id}` as never)} style={styles.rowPressable}>
      {({ pressed }) => (
        <Card style={[styles.row, pressed && styles.rowPressed]} shadowToken="xs">
          <View style={styles.iconWrap}>
            <Ionicons name="warning-outline" size={18} color={colors.accentStrong} />
          </View>
          <View style={styles.rowBody}>
            <View style={styles.titleRow}>
              <Text variant="headline" numberOfLines={1} style={styles.title}>
                {r.templateName}
              </Text>
              <StatusBadge
                label={r.status === 'completed' ? 'Completed' : 'In Progress'}
                tone={r.status === 'completed' ? 'success' : 'warning'}
              />
              {syncState ? <StatusBadge label={SYNC_BADGE[syncState].label} tone={SYNC_BADGE[syncState].tone} /> : null}
            </View>
            <Text variant="footnote" color={colors.textSecondary} numberOfLines={1}>
              {r.trade} ·{' '}
              {r.status === 'completed'
                ? `${identifiedCount} hazard${identifiedCount === 1 ? '' : 's'} identified`
                : `Step ${r.currentStep + 1} of ${TOTAL_STEPS} · ${percent}%`}
            </Text>
            <Text variant="footnote" color={colors.textTertiary} numberOfLines={1}>
              Generated by {personName(r.generatedBy)} · {formatDate(r.generatedAt)}
            </Text>
          </View>
          <Ionicons name="chevron-forward" size={16} color={colors.textTertiary} />
        </Card>
      )}
    </Pressable>
  );
}

const styles = StyleSheet.create({
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  rowPressable: {
    marginBottom: spacing.sm,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md,
  },
  rowPressed: {
    opacity: 0.92,
  },
  iconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.accentMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowBody: {
    flex: 1,
    marginLeft: spacing.sm,
    marginRight: spacing.sm,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: 2,
  },
  title: {
    flexShrink: 1,
  },
});
