import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';

import { EmptyState, GlassCard, Screen, StatusBadge, Text } from '../../../src/components/ui';
import { CHECKLIST_TEMPLATES } from '../../../src/data/company';
import { checklistRecordsForTemplate, formatDate, getJob, personName } from '../../../src/data/selectors';
import { colors, spacing } from '../../../src/theme';

export default function ChecklistTemplateScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const template = CHECKLIST_TEMPLATES.find((t) => t.id === id);

  if (!template) {
    return (
      <Screen glow={false}>
        <EmptyState icon="checkbox-outline" title="Template not found" />
      </Screen>
    );
  }

  const records = checklistRecordsForTemplate(template.id);

  return (
    <Screen glow={false}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} hitSlop={12} style={styles.backButton}>
          <Ionicons name="chevron-back" size={22} color={colors.textPrimary} />
        </Pressable>
      </View>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <View style={styles.inner}>
          <StatusBadge label={template.trade} tone="accent" />
          <Text variant="title1" style={styles.title}>
            {template.name}
          </Text>
          <Text variant="body" color={colors.textSecondary} style={styles.description}>
            {template.description}
          </Text>
          <Text variant="caption1" color={colors.textTertiary}>
            Updated {formatDate(template.updatedAt)} by {personName(template.createdBy)}
          </Text>

          <Text variant="caption1" color={colors.textTertiary} style={styles.sectionLabel}>
            CHECKLIST ITEMS ({template.items.length})
          </Text>
          <GlassCard style={styles.card}>
            {template.items.map((item, index) => (
              <View key={item.id}>
                <View style={styles.itemRow}>
                  <Ionicons name="checkbox-outline" size={16} color={colors.textTertiary} />
                  <Text variant="body" style={styles.itemText}>
                    {item.text}
                  </Text>
                </View>
                {index < template.items.length - 1 ? <View style={styles.divider} /> : null}
              </View>
            ))}
          </GlassCard>

          <Text variant="caption1" color={colors.textTertiary} style={styles.sectionLabel}>
            GENERATED FOR JOBS ({records.length})
          </Text>
          {records.length === 0 ? (
            <GlassCard style={styles.card}>
              <View style={styles.emptyWrap}>
                <Text variant="subhead" color={colors.textTertiary}>
                  Not generated on any job yet
                </Text>
              </View>
            </GlassCard>
          ) : (
            <GlassCard style={styles.card}>
              {records.map((record, index) => (
                <View key={record.id}>
                  <Pressable
                    style={styles.recordRow}
                    onPress={() =>
                      router.push({
                        pathname: '/(app)/job/[id]',
                        params: { id: record.jobId, section: 'checklists' },
                      })
                    }
                  >
                    <View style={styles.recordText}>
                      <Text variant="headline" numberOfLines={1}>
                        {getJob(record.jobId)?.name}
                      </Text>
                      <Text variant="footnote" color={colors.textTertiary} numberOfLines={1}>
                        Generated by {personName(record.generatedBy)} · {formatDate(record.generatedAt)}
                      </Text>
                    </View>
                    <StatusBadge
                      label={record.status === 'completed' ? 'Completed' : 'In Progress'}
                      tone={record.status === 'completed' ? 'success' : 'warning'}
                    />
                  </Pressable>
                  {index < records.length - 1 ? <View style={styles.divider} /> : null}
                </View>
              ))}
            </GlassCard>
          )}

          <Text variant="footnote" color={colors.textTertiary} style={styles.footnote}>
            This template stays unchanged. Employees generate a job-specific copy from it inside a
            Job Folder, and the completed record lives permanently with that job.
          </Text>
        </View>
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  header: {
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.xs,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.surfaceBorder,
  },
  content: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xxl,
    alignItems: 'center',
  },
  inner: {
    width: '100%',
    maxWidth: 640,
  },
  title: {
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
  },
  description: {
    marginBottom: spacing.sm,
  },
  sectionLabel: {
    marginTop: spacing.lg,
    marginBottom: spacing.xs,
    marginLeft: spacing.xxs,
  },
  card: {
    marginBottom: spacing.sm,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
  },
  itemText: {
    marginLeft: spacing.sm,
    flex: 1,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.divider,
    marginLeft: spacing.md,
  },
  recordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md,
  },
  recordText: {
    flex: 1,
    marginRight: spacing.sm,
  },
  emptyWrap: {
    padding: spacing.md,
  },
  footnote: {
    marginTop: spacing.lg,
    textAlign: 'center',
  },
});
