import type { CodeEntry } from './types';

export const CODE_BOOKS = [
  'CSA C22.1 Electrical Code',
  'National Plumbing Code of Canada',
  'National Building Code of Canada',
  'CSA B149.1 Gas Code',
  'CSA B52 Mechanical Refrigeration Code',
];

export const CODE_YEARS = ['2024', '2021', '2018'];

export const CODE_DATABASE: CodeEntry[] = [
  {
    id: 'c-001',
    title: 'Minimum conductor size for 20A branch circuits',
    explanation: '12 AWG copper is the minimum size for a standard 20A residential branch circuit, before any derating.',
    sectionRef: 'Rule 4-004, Table 2',
    codeBook: 'CSA C22.1 Electrical Code',
    trade: 'electrical',
    province: 'ALL',
    year: '2024',
    keywords: ['wire', 'gauge', 'ampacity', 'conductor', 'circuit', '20a'],
  },
  {
    id: 'c-002',
    title: 'Grounding electrode conductor sizing',
    explanation: 'Sizing table for the grounding conductor based on the largest ungrounded service conductor.',
    sectionRef: 'Section 10, Table 16',
    codeBook: 'CSA C22.1 Electrical Code',
    trade: 'electrical',
    province: 'ALL',
    year: '2024',
    keywords: ['ground', 'grounding', 'bonding', 'electrode'],
  },
  {
    id: 'c-003',
    title: 'AFCI protection for dwelling unit branch circuits',
    explanation: 'Arc-fault circuit interrupter protection is required for most 15A and 20A branch circuits supplying outlets in dwelling units.',
    sectionRef: 'Rule 26-724',
    codeBook: 'CSA C22.1 Electrical Code',
    trade: 'electrical',
    province: 'ALL',
    year: '2024',
    keywords: ['afci', 'arc fault', 'breaker', 'protection'],
  },
  {
    id: 'c-004',
    title: 'GFCI protection in wet locations',
    explanation: 'Ground-fault protection is required for receptacles in bathrooms, kitchens, and outdoor locations.',
    sectionRef: 'Rule 26-700',
    codeBook: 'CSA C22.1 Electrical Code',
    trade: 'electrical',
    province: 'ALL',
    year: '2021',
    keywords: ['gfci', 'ground fault', 'wet location', 'bathroom', 'kitchen'],
  },
  {
    id: 'c-005',
    title: 'Working space clearance around panels',
    explanation: 'Electrical panels require 1.0m of dedicated depth clearance and full panel width, floor to 2.0m high.',
    sectionRef: 'Rule 2-308',
    codeBook: 'CSA C22.1 Electrical Code',
    trade: 'electrical',
    province: 'ALL',
    year: '2024',
    keywords: ['clearance', 'panel', 'workspace', 'access'],
  },
  {
    id: 'c-006',
    title: 'Minimum cover for direct-buried conduit in Ontario',
    explanation: 'Direct-buried PVC conduit under trafficked areas needs 450mm minimum cover; 300mm under lawns.',
    sectionRef: 'Table 53 (ON amendment)',
    codeBook: 'CSA C22.1 Electrical Code',
    trade: 'electrical',
    province: 'ON',
    year: '2024',
    keywords: ['conduit', 'buried', 'depth', 'trench', 'pvc'],
  },
  {
    id: 'c-007',
    title: 'Service mast clearance over grade',
    explanation: 'Overhead service conductors need a minimum 3.0m clearance over residential driveways and 5.5m over roads.',
    sectionRef: 'Rule 6-112',
    codeBook: 'CSA C22.1 Electrical Code',
    trade: 'electrical',
    province: 'BC',
    year: '2021',
    keywords: ['service', 'mast', 'clearance', 'overhead'],
  },
  {
    id: 'c-008',
    title: 'Tamper-resistant receptacles in dwelling units',
    explanation: 'All 15A and 20A general-use receptacles in dwelling units must be tamper-resistant.',
    sectionRef: 'Rule 26-712',
    codeBook: 'CSA C22.1 Electrical Code',
    trade: 'electrical',
    province: 'ALL',
    year: '2018',
    keywords: ['receptacle', 'tamper resistant', 'outlet'],
  },
  {
    id: 'p-001',
    title: 'Minimum trap seal depth',
    explanation: 'Plumbing fixture traps must maintain a minimum liquid seal of 50mm to prevent sewer gas intrusion.',
    sectionRef: 'Section 4.5.2',
    codeBook: 'National Plumbing Code of Canada',
    trade: 'plumbing',
    province: 'ALL',
    year: '2021',
    keywords: ['trap', 'seal', 'drain', 'sewer gas'],
  },
  {
    id: 'p-002',
    title: 'Vent stack sizing for fixture units',
    explanation: 'Minimum vent pipe diameter is determined by total fixture units and the developed length of the vent.',
    sectionRef: 'Table 5.5.4',
    codeBook: 'National Plumbing Code of Canada',
    trade: 'plumbing',
    province: 'ALL',
    year: '2021',
    keywords: ['vent', 'stack', 'fixture units', 'sizing'],
  },
  {
    id: 'p-003',
    title: 'Backflow prevention for potable water connections',
    explanation: 'Cross-connections between potable water and non-potable sources require an approved backflow preventer.',
    sectionRef: 'Section 2.6.3',
    codeBook: 'National Plumbing Code of Canada',
    trade: 'plumbing',
    province: 'ALL',
    year: '2024',
    keywords: ['backflow', 'cross connection', 'potable water'],
  },
  {
    id: 'p-004',
    title: 'Minimum slope for horizontal drain piping',
    explanation: 'Drain pipes up to 75mm need a minimum slope of 2%; larger pipes may use 1%.',
    sectionRef: 'Section 4.6.1',
    codeBook: 'National Plumbing Code of Canada',
    trade: 'plumbing',
    province: 'QC',
    year: '2021',
    keywords: ['slope', 'drain', 'grade', 'pipe'],
  },
  {
    id: 'p-005',
    title: 'Water heater temperature and pressure relief valve',
    explanation: 'Every storage water heater requires a T&P relief valve discharging within 150mm of the floor.',
    sectionRef: 'Section 7.6.6',
    codeBook: 'National Plumbing Code of Canada',
    trade: 'plumbing',
    province: 'ALL',
    year: '2018',
    keywords: ['water heater', 'relief valve', 'pressure', 'temperature'],
  },
  {
    id: 'h-001',
    title: 'Combustion air supply for fuel-fired appliances',
    explanation: 'Enclosed fuel-fired appliances need a dedicated combustion air supply sized to the appliance input rating.',
    sectionRef: 'Section 8.2',
    codeBook: 'CSA B149.1 Gas Code',
    trade: 'hvac',
    province: 'ALL',
    year: '2024',
    keywords: ['combustion air', 'furnace', 'appliance', 'ventilation'],
  },
  {
    id: 'h-002',
    title: 'Minimum duct clearance from combustibles',
    explanation: 'Supply and return ducts near furnaces require clearance from combustible materials per the appliance listing.',
    sectionRef: 'Section 5.3',
    codeBook: 'CSA B149.1 Gas Code',
    trade: 'hvac',
    province: 'ALL',
    year: '2021',
    keywords: ['duct', 'clearance', 'combustible', 'furnace'],
  },
  {
    id: 'h-003',
    title: 'Refrigerant piping insulation requirements',
    explanation: 'Suction lines on split-system air conditioners must be insulated for their full accessible length.',
    sectionRef: 'Section 9.4',
    codeBook: 'CSA B52 Mechanical Refrigeration Code',
    trade: 'hvac',
    province: 'AB',
    year: '2021',
    keywords: ['refrigerant', 'piping', 'insulation', 'suction line'],
  },
  {
    id: 'h-004',
    title: 'Condensate drain sizing and slope',
    explanation: 'Condensate drains must be sized to the equipment cooling capacity with a minimum slope of 2%.',
    sectionRef: 'Section 7.1',
    codeBook: 'CSA B52 Mechanical Refrigeration Code',
    trade: 'hvac',
    province: 'ALL',
    year: '2024',
    keywords: ['condensate', 'drain', 'slope', 'cooling'],
  },
  {
    id: 'b-001',
    title: 'Stair rise and run for residential occupancies',
    explanation: 'Residential stairs require a maximum rise of 200mm and minimum run of 210mm.',
    sectionRef: '9.8.4',
    codeBook: 'National Building Code of Canada',
    trade: 'carpentry',
    province: 'ALL',
    year: '2020',
    keywords: ['stair', 'rise', 'run', 'tread'],
  },
  {
    id: 'b-002',
    title: 'Guard height for elevated walking surfaces',
    explanation: 'Guards on surfaces more than 600mm above grade must be at least 900mm high for residential occupancies.',
    sectionRef: '9.8.8',
    codeBook: 'National Building Code of Canada',
    trade: 'carpentry',
    province: 'ALL',
    year: '2020',
    keywords: ['guard', 'railing', 'height', 'deck', 'balcony'],
  },
  {
    id: 'b-003',
    title: 'Fire separation between dwelling units',
    explanation: 'Adjoining dwelling units require a fire separation with a minimum 45-minute fire-resistance rating.',
    sectionRef: '9.10.9',
    codeBook: 'National Building Code of Canada',
    trade: 'carpentry',
    province: 'ON',
    year: '2020',
    keywords: ['fire separation', 'rating', 'wall', 'assembly'],
  },
  {
    id: 'b-004',
    title: 'Minimum ceiling height for habitable rooms',
    explanation: 'Habitable rooms require a minimum unobstructed ceiling height of 2.1m over at least 75% of the area.',
    sectionRef: '9.5.3',
    codeBook: 'National Building Code of Canada',
    trade: 'carpentry',
    province: 'BC',
    year: '2020',
    keywords: ['ceiling', 'height', 'habitable', 'basement'],
  },
  {
    id: 'g-001',
    title: 'Clearance to combustibles for gas appliance vents',
    explanation: 'Gas appliance vent connectors need clearance from combustible material based on the vent listing category.',
    sectionRef: 'Section 7.5',
    codeBook: 'CSA B149.1 Gas Code',
    trade: 'gas_fitting',
    province: 'ALL',
    year: '2024',
    keywords: ['vent', 'clearance', 'combustible', 'gas appliance'],
  },
  {
    id: 'g-002',
    title: 'Gas piping pressure test requirements',
    explanation: 'New gas piping installations require a pressure test held for at least 10 minutes with no perceptible drop.',
    sectionRef: 'Section 6.20',
    codeBook: 'CSA B149.1 Gas Code',
    trade: 'gas_fitting',
    province: 'ALL',
    year: '2021',
    keywords: ['pressure test', 'gas piping', 'leak test'],
  },
  {
    id: 'g-003',
    title: 'Shutoff valve accessibility for gas appliances',
    explanation: 'Every gas appliance requires an accessible shutoff valve within 1.8m of the appliance it serves.',
    sectionRef: 'Section 6.7',
    codeBook: 'CSA B149.1 Gas Code',
    trade: 'gas_fitting',
    province: 'ALL',
    year: '2018',
    keywords: ['shutoff', 'valve', 'accessible', 'appliance'],
  },
  {
    id: 'c-009',
    title: 'Arc-flash labeling for service equipment',
    explanation: 'Service equipment likely to require examination while energized must be field-marked with arc-flash hazard warnings.',
    sectionRef: 'Rule 2-100',
    codeBook: 'CSA C22.1 Electrical Code',
    trade: 'electrical',
    province: 'ALL',
    year: '2024',
    keywords: ['arc flash', 'labeling', 'hazard', 'warning'],
  },
  {
    id: 'c-010',
    title: 'EV charging outlet circuit requirements',
    explanation: 'Electric vehicle supply equipment outlets require a dedicated branch circuit sized for continuous duty at 125% of rated load.',
    sectionRef: 'Rule 86-306',
    codeBook: 'CSA C22.1 Electrical Code',
    trade: 'electrical',
    province: 'ALL',
    year: '2024',
    keywords: ['ev charger', 'electric vehicle', 'dedicated circuit'],
  },
  {
    id: 'p-006',
    title: 'Cleanout spacing for horizontal drain lines',
    explanation: 'Horizontal drain lines require a cleanout at intervals not exceeding 15m for pipes 100mm and larger.',
    sectionRef: 'Section 4.7.2',
    codeBook: 'National Plumbing Code of Canada',
    trade: 'plumbing',
    province: 'ALL',
    year: '2021',
    keywords: ['cleanout', 'drain', 'spacing', 'access'],
  },
  {
    id: 'b-005',
    title: 'Smoke alarm placement requirements',
    explanation: 'Smoke alarms are required on every storey and in every sleeping room, interconnected across the dwelling unit.',
    sectionRef: '9.10.19',
    codeBook: 'National Building Code of Canada',
    trade: 'carpentry',
    province: 'ALL',
    year: '2020',
    keywords: ['smoke alarm', 'detector', 'sleeping room', 'interconnect'],
  },
];
